* configure.in, smtpserver/smtptls.c: .   Know  --enable-distcache  -- code modelled after .   the one in Apache-2.0 mod_ssl module. .   (Distributed Session Cache) * smtpserver/smtpserver.c, smtpserver/smtpserver.h, . smtpserver/smtpauth.c, smtpserver/smtphook.c, . smtpserver/smtp-perl-hooks.pl.in: .   First write-thru of perl-hooks for smtpserver.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -854,6 +854,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-rpath         do not hardcode runtime library paths
   --disable-nls           do not use Native Language Support
+  --enable-distcache=yes/no,  Select distcache support
   --enable-translation=CHS Enable charset translation of incoming text messages.
                            Assumes --generic-library=\"... -lmcs ...\" and
                            proper --generic-include.
@@ -23085,6 +23086,322 @@ fi
 
 
 fi;
+
+
+echo "$as_me:$LINENO: checking whether Distcache is required" >&5
+echo $ECHO_N "checking whether Distcache is required... $ECHO_C" >&6
+ap_ssltk_dc="no"
+tmp_nomessage=""
+tmp_forced="no"
+# Check whether --enable-distcache or --disable-distcache was given.
+if test "${enable_distcache+set}" = set; then
+  enableval="$enable_distcache"
+  ap_ssltk_dc="$enableval"
+  tmp_nomessage=""
+  tmp_forced="yes"
+  if test "x$ap_ssltk_dc" = "x"; then
+    ap_ssltk_dc="yes"
+        tmp_forced="no"
+  fi
+  if test "$ap_ssltk_dc" != "yes" -a "$ap_ssltk_dc" != "no"; then
+    tmp_nomessage="--enable-distcache had illegal syntax - disabling"
+    ap_ssltk_dc="no"
+  fi
+fi;
+if test "$tmp_forced" = "no"; then
+    echo "$as_me:$LINENO: result: $ap_ssltk_dc (default)" >&5
+echo "${ECHO_T}$ap_ssltk_dc (default)" >&6
+else
+    echo "$as_me:$LINENO: result: $ap_ssltk_dc (specified)" >&5
+echo "${ECHO_T}$ap_ssltk_dc (specified)" >&6
+fi
+if test "$tmp_forced" = "yes" -a "x$ap_ssltk_dc" = "xno" -a "x$tmp_nomessage" != "x"; then
+    { { echo "$as_me:$LINENO: error: distcache support failed: $tmp_nomessage" >&5
+echo "$as_me: error: distcache support failed: $tmp_nomessage" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "$ap_ssltk_dc" = "yes"; then
+    if test "${ac_cv_header_distcache_dc_client_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for distcache/dc_client.h" >&5
+echo $ECHO_N "checking for distcache/dc_client.h... $ECHO_C" >&6
+if test "${ac_cv_header_distcache_dc_client_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_distcache_dc_client_h" >&5
+echo "${ECHO_T}$ac_cv_header_distcache_dc_client_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking distcache/dc_client.h usability" >&5
+echo $ECHO_N "checking distcache/dc_client.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <distcache/dc_client.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking distcache/dc_client.h presence" >&5
+echo $ECHO_N "checking distcache/dc_client.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <distcache/dc_client.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: distcache/dc_client.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: distcache/dc_client.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: distcache/dc_client.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: distcache/dc_client.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: distcache/dc_client.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: distcache/dc_client.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: distcache/dc_client.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: distcache/dc_client.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: distcache/dc_client.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ---------------------------------- ##
+## Report this to zmhack@nic.funet.fi ##
+## ---------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for distcache/dc_client.h" >&5
+echo $ECHO_N "checking for distcache/dc_client.h... $ECHO_C" >&6
+if test "${ac_cv_header_distcache_dc_client_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_distcache_dc_client_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_distcache_dc_client_h" >&5
+echo "${ECHO_T}$ac_cv_header_distcache_dc_client_h" >&6
+
+fi
+if test $ac_cv_header_distcache_dc_client_h = yes; then
+  :
+else
+  tmp_nomessage="can't include distcache headers"
+      ap_ssltk_dc="no"
+fi
+
+
+    if test "$tmp_forced" = "yes" -a "x$ap_ssltk_dc" = "xno"; then
+      { { echo "$as_me:$LINENO: error: distcache support failed: $tmp_nomessage" >&5
+echo "$as_me: error: distcache support failed: $tmp_nomessage" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+if test "$ap_ssltk_dc" = "yes"; then
+    echo "$as_me:$LINENO: checking for Distcache version" >&5
+echo $ECHO_N "checking for Distcache version... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <distcache/dc_client.h>
+int
+main ()
+{
+#if DISTCACHE_CLIENT_API != 0x0001
+#error "distcache API version is unrecognised"
+#endif
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+tmp_nomessage="distcache has an unsupported API version"
+ap_ssltk_dc="no"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+    echo "$as_me:$LINENO: result: $ap_ssltk_dc" >&5
+echo "${ECHO_T}$ap_ssltk_dc" >&6
+    if test "$tmp_forced" = "yes" -a "x$ap_ssltk_dc" = "xno"; then
+      { { echo "$as_me:$LINENO: error: distcache support failed: $tmp_nomessage" >&5
+echo "$as_me: error: distcache support failed: $tmp_nomessage" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+if test "$ap_ssltk_dc" = "yes"; then
+    echo "$as_me:$LINENO: checking for Distcache libraries" >&5
+echo $ECHO_N "checking for Distcache libraries... $ECHO_C" >&6
+    save_libs=$LIBS
+    LIBS="$LIBS -ldistcache -lnal"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <distcache/dc_client.h>
+int
+main ()
+{
+DC_CTX *foo = DC_CTX_new((const char *)0,0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+tmp_no_message="failed to link with distcache libraries"
+      ap_ssltk_dc="no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    LIBS=$save_libs
+    echo "$as_me:$LINENO: result: $ap_ssltk_dc" >&5
+echo "${ECHO_T}$ap_ssltk_dc" >&6
+    if test "$tmp_forced" = "yes" -a "x$ap_ssltk_dc" = "xno"; then
+      { { echo "$as_me:$LINENO: error: distcache support failed: $tmp_nomessage; need  --generic-include and/or --generic-lib ?" >&5
+echo "$as_me: error: distcache support failed: $tmp_nomessage; need  --generic-include and/or --generic-lib ?" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+
+if test "$ap_ssltk_dc" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DISTCACHE 1
+_ACEOF
+
+    OPENSSLLIB="$OPENSSLLIB -ldistcache -lnal"
+fi
+
 
 
 
