A few fixes for 'vacation' -- DB(M) handling had some inconsistensies -- like double-close of the database which caused occasional core by the utility. Also automate the installation procedure into userspace.

diff --git a/utils/vacation/Makefile.in b/utils/vacation/Makefile.in
--- a/utils/vacation/Makefile.in
+++ b/utils/vacation/Makefile.in
@@ -1,3 +1,7 @@
+#
+#  Makefile(.in) for ZMailer's vacation program
+#
+
 srcdir = @srcdir@
 VPATH = @srcdir@
 @SET_MAKE@
@@ -16,6 +20,7 @@ LIBS=		-L$(TOPDIR)/libs -lzc @GETPWLIB@ @LIBRESOLV@ @LIBSOCKET@
 
 VMSGDEF=	@MAILSHARE@/vacation.msg
 DEFS=		@DEFS@ -DVMSGDEF='"$(VMSGDEF)"'
+VACATIONPATH=	$(prefix)@VACATIONPATH@
 
 INCL=		-I$(srcdir)/$(TOPDIR)/include -I$(TOPDIR)/include -I$(TOPDIR)
 DBMLIB=		@LIBDBMS@
@@ -43,13 +48,36 @@ clean:
 distclean: clean
 	rm -f Makefile vacation.sh $(TOPDIR)/man/vacation.1
 
-install: vacation
+install: vacation-inst
+	@if [ $(LN_S) = "ln -s" -a					\
+	     "$(VACATIONPATH)" != "$(MAILBIN)/vacation.sh" ]; then	\
+	    if [ -h $(VACATIONPATH) ]; then				\
+		test -f $(VACATIONPATH) &&				\
+			rm -f $(VACATIONPATH) ;				\
+		echo "ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH)" ;	\
+		ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH) ||		\
+			echo "Failed! rc=$?" ;				\
+	    else							\
+		test -f $(VACATIONPATH) &&				\
+			mv -f $(VACATIONPATH) $(VACATIONPATH).orig;	\
+		echo "ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH)";	\
+		ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH) ||		\
+			echo "Failed! rc=$?" ;				\
+	    fi ;							\
+	else								\
+	    echo "********************************************************" ; \
+	    echo "** $(VACATIONPATH) needs to be updated to be" ;  	      \
+	    echo "**   a symlink (if possible) to $(MAILBIN)/vacation.sh" ;  \
+	    echo "********************************************************" ; \
+	fi
+
+vacation-inst: vacation
 	@$(INSTALL) -m 755 vacation.sh $(MAILBIN)/vacation.sh
 	-@rm -f $(MAILBIN)/vacation
 	@cd $(MAILBIN) ; ln -s vacation.sh vacation
 	@$(INSTALL) -m 755 vacation $(MAILBIN)/vacation.exe
 	@if [ ! -f $(prefix)$(VMSGDEF) ] ; then				\
-		$(INSTALL) -m 644 $(srcdir)/vacation.msg $(prefix)$(VMSGDEF) ; \
+		$(INSTALL) -m 644 $(srcdir)/vacation.msg $(prefix)$(VMSGDEF); \
 	else								\
 		echo "** File $(prefix)$(VMSGDEF) already installed" ;	\
 	fi
