See ChangeLog;  configure.in -ldb vs. -ldb1 tests, some vacation things.

diff --git a/utils/vacation/Makefile.in b/utils/vacation/Makefile.in
--- a/utils/vacation/Makefile.in
+++ b/utils/vacation/Makefile.in
@@ -12,6 +12,7 @@ COPTS=		@CFLAGS@
 CPPFLAGS=	@CPPFLAGS@
 CPPDEP=		@CPPDEP@
 MAILBIN=	$(prefix)@MAILBIN@
+MAILBIN_=	@MAILBIN@
 MAILSHARE=	$(prefix)@MAILSHARE@
 MANDIR=		$(prefix)@MANDIR@
 INSTALL=	@INSTALL@
@@ -51,20 +52,22 @@ distclean: clean
 	rm -f Makefile vacation.sh $(TOPDIR)/man/vacation.1
 
 install: vacation-inst
+	@VACATIONDIR=`echo $(VACATIONPATH) | sed -e 's!/[^/]$$!!'` ; \
+	if [ ! -d $$(VACATIONDIR) ] ; then mkdir -p -m 755 $$(VACATIONDIR) ; fi
 	@if [ $(LN_S) = "ln -s" -a					\
 	     "$(VACATIONPATH)" != "$(MAILBIN)/vacation.sh" ]; then	\
 	    if [ -h "$(VACATIONPATH)" ]; then				\
-		test -f $(VACATIONPATH) &&				\
-			rm -f $(VACATIONPATH) ;				\
-		echo "ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH)" ;	\
-		ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH) ||		\
-			echo "Failed! rc=$?" ;				\
+		test -f "$(VACATIONPATH)" &&				\
+			rm -f "$(VACATIONPATH)" ;			\
+		echo "ln -s $(MAILBIN_)/vacation.sh $(VACATIONPATH)" ;	\
+		ln -s $(MAILBIN_)/vacation.sh $(VACATIONPATH) ||	\
+			echo "Failed! rc=$$?" ;				\
 	    else							\
 		test -f "$(VACATIONPATH)" &&				\
 			mv -f $(VACATIONPATH) $(VACATIONPATH).orig;	\
-		echo "ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH)";	\
-		ln -s $(MAILBIN)/vacation.sh $(VACATIONPATH) ||		\
-			echo "Failed! rc=$?" ;				\
+		echo "ln -s $(MAILBIN_)/vacation.sh $(VACATIONPATH)";	\
+		ln -s $(MAILBIN_)/vacation.sh $(VACATIONPATH) ||	\
+			echo "Failed! rc=$$?" ;				\
 	    fi ;							\
 	else								\
 	    echo "********************************************************" ; \
