* utils/policy-builder.sh.in, utils/makedb/makedb.c: .   "makedb -p" crashed in some situations, fixed .   NULL referral.  Also report about exit code of .   the makedb  in  policy-builder.sh  script.

diff --git a/utils/policy-builder.sh.in b/utils/policy-builder.sh.in
--- a/utils/policy-builder.sh.in
+++ b/utils/policy-builder.sh.in
@@ -183,7 +183,14 @@ umask 022 # Make sure the resulting db file(s) are readable by all
 # has same key repeating, append latter data instances to the first
 # one (-A):
 
-$MAILBIN/makedb -A -p $DBTYPE smtp-policy-new smtp-policy.dat || exit $?
+if $MAILBIN/makedb -A -p $DBTYPE smtp-policy-new smtp-policy.dat
+then
+  :
+else
+  rc=$?
+  echo "smtp-policy control database makedb failure rc= $rc"
+  exit $rc
+fi
 
 case $DBTYPE in
 dbm)
